---

- block:

    - name: check current shellcheck
      ansible.builtin.stat:
        path: "{{ system_tools_shellcheck_local_bin }}"
      register: t_system_tools_shellcheck_local_bin

    - block:

        - name: get latest shellcheck version from GitHub API
          ansible.builtin.uri:
            url: "{{ system_tools_shellcheck_github_api_latest_url }}"
            return_content: yes
          register: t_system_tools_shellcheck_github_latest_release
          changed_when: no

        - name: extract latest shellcheck version
          ansible.builtin.set_fact:
            system_tools_shellcheck_version: "{{ (t_system_tools_shellcheck_github_latest_release.content | from_json).tag_name | replace('v', '') }}"

      when: system_tools_shellcheck_version is not defined or system_tools_shellcheck_version == ""

    - block:

        - name: get current shellcheck version
          ansible.builtin.shell:
            cmd: "{{ system_tools_shellcheck_local_bin }} -V | sed -n 's/^version: \\([0-9.]*\\)/\\1/p'"
          register: t_system_tools_shellcheck_current_version
          changed_when: no

      when: t_system_tools_shellcheck_local_bin.stat.exists

    # - debug:
    #     msg: "latest:{{ system_tools_shellcheck_version }}  -  current:{{ t_system_tools_shellcheck_current_version.stdout | d('') }}"

    - block:

        - name: download shellcheck archive
          ansible.builtin.get_url:
            url: "{{ system_tools_shellcheck_github_download_url }}"
            dest: "{{ system_tmp_dir }}/shellcheck.tar.xz"
            mode: '0644'

        - name: extract shellcheck archive
          ansible.builtin.unarchive:
            src: "{{ system_tmp_dir }}/shellcheck.tar.xz"
            dest: "{{ system_tmp_dir }}"
            remote_src: yes
            creates: "{{ system_tmp_dir }}/{{ system_tools_shellcheck_name }}"

        - name: "install shellcheck binary to {{ system_tools_shellcheck_local_bin }}"
          ansible.builtin.copy:
            src: "{{ system_tmp_dir }}/{{ system_tools_shellcheck_name }}-v{{ system_tools_shellcheck_version }}/{{ system_tools_shellcheck_name }}"
            dest: "{{ system_tools_shellcheck_local_bin }}"
            mode: '0755'
            owner: root
            group: root
            remote_src: yes

        - name: clean up temporary files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ system_tmp_dir }}/shellcheck.tar.xz"
            - "{{ system_tmp_dir }}/{{ system_tools_shellcheck_name }}-v{{ system_tools_shellcheck_version }}"

      when: not t_system_tools_shellcheck_local_bin.stat.exists or (t_system_tools_shellcheck_current_version is defined and t_system_tools_shellcheck_current_version.stdout != system_tools_shellcheck_version)

  when: want_system_tools_shellcheck
